#!/usr/bin/env python3
"""Generate all required secrets for a new TidePool deployment.

Produces:
    SECRET_KEY      -- 64-character random string for JWT signing.
    ENCRYPTION_KEY  -- Valid Fernet key for field-level encryption.
    DB_PASSWORD     -- 32-character random string for PostgreSQL.

Usage:
    python generate_secrets.py                     # Print as .env format (default)
    python generate_secrets.py --format docker     # Print as docker compose env entries
    python generate_secrets.py --format json       # Print as JSON
    python generate_secrets.py --append-to .env    # Append directly to a .env file

Exit codes:
    0  Success
    1  Error (file write failure, etc.)
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import secrets
import sys
from pathlib import Path


def generate_secret_key(length: int = 64) -> str:
    """Generate a cryptographically secure random string."""
    return secrets.token_urlsafe(length)[:length]


def generate_fernet_key() -> str:
    """Generate a valid Fernet key (URL-safe base64 of 32 random bytes)."""
    return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def generate_db_password(length: int = 32) -> str:
    """Generate a random database password (alphanumeric + limited symbols)."""
    # Avoid characters that are problematic in connection strings.
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_all() -> dict[str, str]:
    """Generate all secrets and return as a dict."""
    return {
        "SECRET_KEY": generate_secret_key(64),
        "ENCRYPTION_KEY": generate_fernet_key(),
        "DB_PASSWORD": generate_db_password(32),
    }


# ---------------------------------------------------------------------------
# Output formatters
# ---------------------------------------------------------------------------

def format_env(secrets_dict: dict[str, str]) -> str:
    """Format as .env file entries."""
    lines = [
        "# TidePool secrets -- generated by generate_secrets.py",
        "# Keep this file secure and out of version control.",
        "",
    ]
    for key, value in secrets_dict.items():
        lines.append(f"{key}={value}")
    lines.append("")
    return "\n".join(lines)


def format_docker(secrets_dict: dict[str, str]) -> str:
    """Format as docker compose environment entries (indented YAML)."""
    lines = [
        "# Add these to your docker-compose.yml environment section:",
        "",
    ]
    for key, value in secrets_dict.items():
        lines.append(f"      - {key}={value}")
    lines.append("")
    return "\n".join(lines)


def format_json(secrets_dict: dict[str, str]) -> str:
    """Format as JSON."""
    return json.dumps(secrets_dict, indent=2)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate secrets for a new TidePool deployment.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--format", choices=["env", "docker", "json"], default="env",
        help="Output format (default: env).",
    )
    parser.add_argument(
        "--append-to", metavar="FILE",
        help="Append the generated secrets to the specified file (e.g., .env).",
    )
    parser.add_argument(
        "--secret-key-length", type=int, default=64,
        help="Length of the SECRET_KEY (default: 64).",
    )
    parser.add_argument(
        "--db-password-length", type=int, default=32,
        help="Length of the DB_PASSWORD (default: 32).",
    )
    args = parser.parse_args()

    # Validate lengths.
    if args.secret_key_length < 32:
        print("ERROR: SECRET_KEY must be at least 32 characters.", file=sys.stderr)
        return 1
    if args.db_password_length < 16:
        print("ERROR: DB_PASSWORD must be at least 16 characters.", file=sys.stderr)
        return 1

    # Generate.
    secrets_dict = {
        "SECRET_KEY": generate_secret_key(args.secret_key_length),
        "ENCRYPTION_KEY": generate_fernet_key(),
        "DB_PASSWORD": generate_db_password(args.db_password_length),
    }

    # Format output.
    formatters = {
        "env": format_env,
        "docker": format_docker,
        "json": format_json,
    }
    output = formatters[args.format](secrets_dict)

    # Append to file or print.
    if args.append_to:
        target = Path(args.append_to)
        try:
            # Ensure we add a newline separator if file already has content.
            separator = ""
            if target.is_file() and target.stat().st_size > 0:
                with open(target, "rb") as f:
                    f.seek(-1, 2)
                    if f.read(1) != b"\n":
                        separator = "\n"
                separator += "\n"

            with open(target, "a") as f:
                f.write(separator)
                f.write(output)

            print(f"Secrets appended to {target}")
            print()
            print("Generated values:")
            for key in secrets_dict:
                # Show only a prefix for security.
                val = secrets_dict[key]
                print(f"  {key} = {val[:12]}...")

        except OSError as exc:
            print(f"ERROR: Cannot write to {target}: {exc}", file=sys.stderr)
            return 1
    else:
        print(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
