"""Tracking endpoints for email opens, link clicks, and credential submissions.

Privacy design
--------------
These endpoints handle sensitive data from phishing simulation targets.
The following safeguards are in place:

1. Credential submission payloads are NEVER logged in full. Only the field
   *names* (keys) are recorded for audit purposes -- never the values.
2. After processing, the raw submission body is scrubbed from the ASGI
   request scope to prevent upstream middleware or access logs from
   inadvertently capturing credential data.
3. Responses are intentionally uniform regardless of whether a tracking
   token exists, preventing token enumeration.
4. Tracking tokens are validated against a strict format before any
   database lookup to avoid injection or scanning attacks.
"""

from __future__ import annotations

import logging
import re
from typing import Any

import redis.asyncio as aioredis
from fastapi import APIRouter, Depends, Request, Response
from fastapi.responses import HTMLResponse, RedirectResponse
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import get_db
from app.models.campaign import Campaign
from app.tracking.realtime import RealtimeTracker
from app.tracking.recorder import EventRecorder

router = APIRouter(prefix="/t")

logger = logging.getLogger(__name__)

# Tracking tokens are generated by secrets.token_urlsafe(32) which
# produces a 43-character base64url string (no padding).  We accept
# tokens between 32 and 64 characters of URL-safe base64 characters.
_TOKEN_PATTERN = re.compile(r"^[A-Za-z0-9_-]{32,64}$")

# Composite tracking IDs use the format ``{campaign_id}.{token}``.
_COMPOSITE_PATTERN = re.compile(r"^(\d+)\.([A-Za-z0-9_-]{32,64})$")


def _get_recorder() -> tuple[EventRecorder, aioredis.Redis]:
    """Build an EventRecorder and its underlying Redis client.

    Returns (recorder, redis_client) so the caller can close Redis after use.
    """
    redis_client = aioredis.from_url(settings.REDIS_URL, decode_responses=True)
    rt = RealtimeTracker(redis_client)
    return EventRecorder(rt), redis_client


def _validate_tracking_id(tracking_id: str) -> bool:
    """Return True if *tracking_id* matches an accepted token format."""
    return bool(_TOKEN_PATTERN.match(tracking_id)) or bool(
        _COMPOSITE_PATTERN.match(tracking_id)
    )


def _parse_tracking_id(tracking_id: str) -> tuple[int | None, str]:
    """Extract campaign_id and recipient token from a tracking_id.

    Supports two formats:
    - ``{campaign_id}.{token}`` -- returns (campaign_id, token)
    - ``{token}`` -- returns (None, token)
    """
    m = _COMPOSITE_PATTERN.match(tracking_id)
    if m:
        return int(m.group(1)), m.group(2)
    return None, tracking_id


# -- Local schemas ---------------------------------------------------------


class SubmissionPayload(BaseModel):
    """Data submitted from a landing page credential-capture form."""

    fields: dict[str, Any]


# -- Constants -------------------------------------------------------------

# 1x1 transparent GIF for open tracking.
_TRACKING_PIXEL = (
    b"\x47\x49\x46\x38\x39\x61\x01\x00\x01\x00\x80\x00\x00"
    b"\xff\xff\xff\x00\x00\x00\x21\xf9\x04\x00\x00\x00\x00"
    b"\x00\x2c\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02"
    b"\x44\x01\x00\x3b"
)

# Consistent response returned for all submission requests, whether the
# token is valid or not, to prevent enumeration.
_SUBMISSION_ACK = {"status": "ok"}

_THANK_YOU_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Thank You</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
background:#f0f4f8;color:#1a2a3a;margin:0;padding:0;display:flex;
align-items:center;justify-content:center;min-height:100vh}
.card{background:#fff;border-radius:8px;box-shadow:0 1px 4px rgba(0,0,0,.08);
padding:2.5rem;max-width:480px;text-align:center}
h1{font-size:1.5rem;margin-bottom:1rem;color:#1a5276}
p{color:#4a6a8a;line-height:1.6}
</style>
</head>
<body>
<div class="card">
<h1>Thank You</h1>
<p>Your submission has been received.</p>
</div>
</body>
</html>"""


# -- Endpoints -------------------------------------------------------------


@router.get("/o/{tracking_id}")
async def track_open(
    tracking_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Record an email-open event and return a 1x1 transparent pixel.

    The tracking_id encodes the campaign and recipient. The event is
    persisted to the database and pushed to the Redis real-time feed.
    """
    _pixel_response = Response(
        content=_TRACKING_PIXEL,
        media_type="image/gif",
        headers={
            "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
        },
    )

    if not _validate_tracking_id(tracking_id):
        return _pixel_response

    campaign_id, token = _parse_tracking_id(tracking_id)
    if campaign_id is None:
        return _pixel_response

    ip = request.client.host if request.client else "unknown"
    ua = request.headers.get("user-agent", "")
    metadata = {"user_agent": ua, "ip_address": ip}

    # Graceful degradation: if DB/Redis write fails, still return the pixel.
    redis_client = None
    try:
        recorder, redis_client = _get_recorder()
        await recorder.record_open(campaign_id, token, metadata, db)
    except Exception:
        logger.warning("Failed to record open event for %s (non-fatal)", tracking_id, exc_info=True)
    finally:
        if redis_client is not None:
            try:
                await redis_client.aclose()
            except Exception:
                pass

    return _pixel_response


@router.get("/c/{tracking_id}")
async def track_click(
    tracking_id: str,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Record a link-click event and redirect to the landing page.

    After logging the click event, redirects the user to the campaign's
    landing page. If no landing page is configured but a
    training_redirect_url is set, redirects there directly.

    Returns a consistent response regardless of token validity to
    prevent enumeration.
    """
    if not _validate_tracking_id(tracking_id):
        return HTMLResponse(content=_THANK_YOU_HTML, status_code=200)

    campaign_id, token = _parse_tracking_id(tracking_id)

    ip = request.client.host if request.client else "unknown"
    ua = request.headers.get("user-agent", "")
    url = str(request.url)
    metadata = {"user_agent": ua, "ip_address": ip}

    # Persist click event (graceful degradation).
    if campaign_id is not None:
        redis_client = None
        try:
            recorder, redis_client = _get_recorder()
            await recorder.record_click(campaign_id, token, url, metadata, db)
        except Exception:
            logger.warning("Failed to record click event for %s (non-fatal)", tracking_id, exc_info=True)
        finally:
            if redis_client is not None:
                try:
                    await redis_client.aclose()
                except Exception:
                    pass

    if campaign_id is not None:
        campaign = await db.get(Campaign, campaign_id)
        if campaign is not None:
            # If a landing page is configured, the click redirects there.
            # The landing page form submission handles the training redirect.
            if campaign.landing_page_id is not None:
                # TODO: resolve landing page URL from campaign.landing_page
                pass
            elif campaign.training_redirect_url:
                # No landing page -- redirect directly to training.
                return RedirectResponse(
                    url=campaign.training_redirect_url,
                    status_code=302,
                )

    return HTMLResponse(content=_THANK_YOU_HTML, status_code=200)


@router.post("/s/{tracking_id}")
async def track_submission(
    tracking_id: str,
    payload: SubmissionPayload,
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> Response:
    """Record credentials or form data submitted from a landing page.

    After logging the submission, redirects the user to the campaign's
    training_redirect_url if one is configured. Otherwise returns a
    minimal thank-you page.

    Privacy safeguards:
    - Only field NAMES (keys) are logged, never values.
    - The raw request body is scrubbed from the ASGI scope after processing.
    - The response is identical regardless of token validity.
    """
    if not _validate_tracking_id(tracking_id):
        # Scrub body and return consistent response.
        request.scope.pop("body", None)
        return HTMLResponse(content=_THANK_YOU_HTML, status_code=200)

    # Log only field names for audit trail -- never the values.
    field_names = list(payload.fields.keys())
    logger.info(
        "Credential submission received: tracking_id=%s field_names=%s",
        tracking_id,
        field_names,
    )

    campaign_id, token = _parse_tracking_id(tracking_id)

    ip = request.client.host if request.client else "unknown"
    ua = request.headers.get("user-agent", "")
    metadata = {"user_agent": ua, "ip_address": ip}

    # Persist submission event (graceful degradation).
    if campaign_id is not None:
        redis_client = None
        try:
            recorder, redis_client = _get_recorder()
            await recorder.record_submission(campaign_id, token, field_names, metadata, db)
        except Exception:
            logger.warning("Failed to record submission event for %s (non-fatal)", tracking_id, exc_info=True)
        finally:
            if redis_client is not None:
                try:
                    await redis_client.aclose()
                except Exception:
                    pass

    # Scrub the raw submission body from the ASGI scope so that upstream
    # middleware (access logs, error reporters) cannot inadvertently leak
    # credential data.
    request.scope.pop("body", None)
    request._body = b""  # noqa: SLF001  -- intentional scope cleanup

    # Redirect to the campaign's training URL if configured.
    if campaign_id is not None:
        campaign = await db.get(Campaign, campaign_id)
        if campaign is not None and campaign.training_redirect_url:
            return RedirectResponse(
                url=campaign.training_redirect_url,
                status_code=302,
            )

    return HTMLResponse(content=_THANK_YOU_HTML, status_code=200)
